;SAVE"Resrc.Asm"
*--------------------------------
         RSRC    ALRT,1,resPurgeable
         DATA    /149,/15,/239,/290
         DATA    /1
         DATA    /$5555
         ENDR
*--------------------------------
         RSRC    DITL,1,resPurgeable
         DATA    /2-1
         DATA    0
         DATA    /60,/205,/80,/265
         DATA    #4
         STR     "OK"
         DATA    0
         DATA    /27,/72,/43,/265
         DATA    #8+128
         STR     "^0 error."
         HEX     00
         ENDR
*--------------------------------
         RSRC    WIND,128,resPurgeable
         DATA    /49,/12,/326,/499
         DATA    /0
         DATA    #1,#0
         DATA    #0,#0
         DATA    0
         HEX     0114 ;Apple Char.
         ENDR
*--------------------------------
         RSRC    WIND,129,resPurgeable
         DATA    /50,/50,/129,/245
         DATA    /2
         DATA    #1,#0
         DATA    #0,#0
         DATA    0
         STR     ""
         ENDR
*--------------------------------
         RSRC    MASM,0,resPurgeable
         STR     "MacASM v1.4 -- 11/10/86"
         ENDR
*--------------------------------
         RSRC    ICN#,128,resPurgeable
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000019999998
         HEX     7FFFFFFE40000002
         HEX     4000000240000002
         HEX     4000000278000002
         HEX     48003F0248004082
         HEX     4800804248013022
         HEX     7801C812400E7F0F
         HEX     4002300740010007
         HEX     400080077FFFE007
         HEX     19999FE70000001F
         HEX     0000000700000000
         HEX     0000000000000000
*
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000000000000
         HEX     0000000019999998
         HEX     7FFFFFFE7FFFFFFE
         HEX     7FFFFFFE7FFFFFFE
         HEX     7FFFFFFE7FFFFFFE
         HEX     7FFFFFFE7FFFFFFE
         HEX     7FFFFFFE7FFFFFFE
         HEX     7FFFFFFE7FFFFFFF
         HEX     7FFFFFFF7FFFFFFF
         HEX     7FFFFFFF7FFFFFFF
         HEX     19999FFF0000001F
         HEX     0000000700000000
         HEX     0000000000000000
         ENDR
*--------------------------------
         RSRC    ICN#,129,resPurgeable
         HEX     1FFFFE0010000300
         HEX     1000028010000240
         HEX     1000022010000210
         HEX     100003F810000008
         HEX     1000000810666608
         HEX     11FFFF8811000088
         HEX     1100008811C00088
         HEX     1140008811400088
         HEX     11C0008811000088
         HEX     1100008811FFFF88
         HEX     1066660810000008
         HEX     1000000811C7A208
         HEX     1228360812282A08
         HEX     13E722081220A208
         HEX     1220A208122F2208
         HEX     100000081FFFFFF8
*
         HEX     1FFFFE001FFFFF00
         HEX     1FFFFF801FFFFFC0
         HEX     1FFFFFE01FFFFFF0
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         ENDR
*--------------------------------
         RSRC    ICN#,130,resPurgeable
         HEX     1FFFFE0010000300
         HEX     1000028010000240
         HEX     1000022010000210
         HEX     100003F810000008
         HEX     1000000810666608
         HEX     11FFFF8811000088
         HEX     1100008811C00088
         HEX     1140008811400088
         HEX     11C0008811000088
         HEX     1100008811FFFF88
         HEX     1066660810000008
         HEX     1000000813E8BE08
         HEX     1088880810850808
         HEX     1082080810850808
         HEX     1088880810888808
         HEX     100000081FFFFFF8
*
         HEX     1FFFFE001FFFFF00
         HEX     1FFFFF801FFFFFC0
         HEX     1FFFFFE01FFFFFF0
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         ENDR
*--------------------------------
         RSRC    ICN#,131,resPurgeable
         HEX     1FFFFE0010000300
         HEX     1000028010000240
         HEX     1000022010000210
         HEX     100003F810000008
         HEX     1000000810666608
         HEX     11FFFF8811000088
         HEX     1100008811C00088
         HEX     1140008811400088
         HEX     11C0008811000088
         HEX     1100008811FFFF88
         HEX     1066660810000008
         HEX     1000000813C72208
         HEX     1222320812222A08
         HEX     13C2260812222208
         HEX     1222220813C72208
         HEX     100000081FFFFFF8
*
         HEX     1FFFFE001FFFFF00
         HEX     1FFFFF801FFFFFC0
         HEX     1FFFFFE01FFFFFF0
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         HEX     1FFFFFF81FFFFFF8
         ENDR
*--------------------------------
         RSRC    FREF,128,resPurgeable
         DATA    TYPAPL
         DATA    /0
         STR     ""
         ENDR
*--------------------------------
         RSRC    FREF,129,resPurgeable
         DATA    TYPSRC
         DATA    /1
         STR     ""
         ENDR
*--------------------------------
         RSRC    FREF,130,resPurgeable
         DATA    TYPTXT
         DATA    /2
         STR     ""
         ENDR
*--------------------------------
         RSRC    FREF,131,resPurgeable
         DATA    TYPBIN
         DATA    /3
         STR     ""
         ENDR
*--------------------------------
         RSRC    BNDL,128,resPurgeable
         DATA    CREAT
         DATA    /0
         DATA    /1
         ASC     'ICN#'
         DATA    /3
         DATA    /0,/128
         DATA    /1,/129
         DATA    /2,/130
         DATA    /3,/131
         ASC     'FREF'
         DATA    /3
         DATA    /0,/128
         DATA    /1,/129
         DATA    /2,/130
         DATA    /3,/131
         ENDR
*--------------------------------
         RSRC    YVES,0,resPreLoad
         DATA    #'W,#'T,/$35E7,#$BE,#$C0
         ENDR
*--------------------------------
